config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  get '/list', to: 'pages#list'
  get '/:url', to:'pages#redirect'
end

app/models/concerns/url_short.rb
module UrlShort
  extend ActiveSupport::Concern

  def generate_short
    (0...6).map { (65 + rand(26)).chr }.join
  end
end

app/models/url.rb
class Url < ActiveRecord::Base
  include UrlShort

  before_save :set_short_url

  def set_short_url
    5.times do
      short = generate_short
      found = self.class.find_by_short short
      unless found
        self.short = short
        return
      end
    end
    raise ShortGenerateError, "can't generate short url"
  end
end

class ShortGenerateError < StandardError

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    if params[:url] && !params[:url].empty?
      @url = find_url || Url.create(short: @short, original: params[:url])
      @short = @url.short
    end
  end

  def redirect
    @url = identify_url
    redirect_to @url ? @url.original : root_path
  end

  def list
    @urls = Url.all
  end

  private

  def find_url
    Url.where(original: params[:url]).first
  end

  def identify_url
    Url.where(short: params[:url]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="zmateusz">
    <link rel="icon" href="../../favicon.ico">
    <title>UrlShortener</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="/">Home</a></li>
            <li role="presentation"><a href="<%= list_path %>">List</a></li>
            <li role="presentation"><a href="#">About</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Url Shortener</h3>
      </div>
      <%= yield %>
      
 <!--      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div> -->

      <footer class="footer">
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h2>Hello!</h2>
  <p class="lead">Make long links short.</p>

  <% if @short %>
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <%= params[:url] %><strong> - short url added</strong><br>
      <input class="form-control" id="short_url" value="<%= "#{root_url}?i=#{@short}" %>" type="text" name="short_url" onClick="this.setSelectionRange(0, this.value.length)">
    </div>
  <% end %>
  
  <form class="form-horizontal" action="/" method="get">
    <fieldset>
      <div class="form-group">
        <label for="url" class="col-lg-2 control-label">URL</label>
        <div class="col-lg-10">
          <input class="form-control" id="url" placeholder="paste url here" type="text" name="url">
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <button type="submit" class="btn btn-primary">Submit</button>
          <button type="reset" class="btn btn-default">Clear</button>
        </div>
      </div>
    </fieldset>
  </form>
  
</div>

app/views/pages/list.html.erb
<% @urls.each do |url| %>
    <%= "#{url.short} - #{url.original}" %>
    <br>
<% end %>